baseURL = 'https://alparslan.dev/'
languageCode = 'tr-TR'
title = 'Ahmed Alparslan Özdemir'
theme = 'archie'
paginate = 5



[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	subtitle = "Yazılım sektöründe tam zamanlı isviçre çakısı, girişimci ve full stack geliştirici. Grafik programlama, oyun geliştirme ve mekatronik meraklısı."
