baseURL = 'https://alparslan.dev/'
languageCode = 'tr-TR'
title = 'Ahmed Alparslan Özdemir'
theme = 'archie'
paginate = 5

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/alparslanahmed"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/alparslanahmed/"

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	subtitle = "Yazılım sektöründe tam zamanlı isviçre çakısı, girişimci ve full stack geliştirici. Grafik programlama, oyun geliştirme ve mekatronik meraklısı."
